# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "documentcloud"

  config.vm.network :private_network, ip: "192.168.33.10"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.aliases = %w(dev.dcloud.org)

  config.vm.synced_folder "./documentcloud/", "/home/vagrant/documentcloud"
end
